### ISSUE TITLE
블로그 메인 Example

### ISSUE THREAD

**Issue by BKJang** [im-d-team/im-d.dev#3]
jbee님의 블로그를 벤치마킹하면 좋을 것 같은데 어떻게 생각하시나요?
- https://github.com/JaeYeopHan/gatsby-starter-bee
- https://jbee.io/

### Detail

- 헤더: 우리는 로고만 들어갈 듯 합니다.(검색 기능이 생길 수 있으면 검색창 정도 들어갈 수 있겠네요)
- 프로필 부분: 우리 스터디에 관련된 여러 링크나 Dev-Docs 링크 등이 있으면 좋겠네여
- 컨텐츠: 글 목록은 현재 우리와 거의 비슷한 것 같긴한데 해당 글을 작성하는데 참여한 contributor들도 같이 표시해주면 좋을 듯 합니다. ([관련 이슈](https://github.com/im-d-team/im-d-team.github.io/issues/4))
- 푸터: 없애도 될 것 같은데 어떠신가요?
- 태그: 태그는 저희 현재 방식을 유지하면 좋을 듯 합니다.(추후 검색 기능이 생기면 빼더라도)

**Comment by SeonHyungJo** [comment]
- [ ] 메뉴를 상단에서 내리도록 || Nav 덮어지고 어둡게
